import streamlit as st

st.set_page_config(
    page_title="Farmer Revenue Optimizer",
    page_icon="🌾",
    layout="wide",
    initial_sidebar_state="expanded",
)

if "lang" not in st.session_state:
    st.session_state["lang"] = "en"


def lang_toggle():
    col1, col2 = st.columns([8, 2])
    with col2:
        choice = st.radio(
            "Language / भाषा",
            options=["English", "हिंदी"],
            index=0 if st.session_state["lang"] == "en" else 1,
            horizontal=True,
            key="lang_radio_home",
        )
        st.session_state["lang"] = "en" if choice == "English" else "hi"


lang_toggle()
lang = st.session_state["lang"]

if lang == "hi":
    st.title("🌾 किसान राजस्व अनुकूलक")
    st.subheader("कम लागत में अधिक आय — आपके खेत के लिए, आपकी भाषा में")
    st.markdown(
        """
        **यह ऐप क्या करता है?**

        - 🗺️ आपके खेत का सटीक स्थान उपग्रह मानचित्र पर चुनें
        - 📋 अपनी फसल, एकड़ और लागत का विवरण दर्ज करें
        - 📊 पाएं: राजस्व अनुमान, लागत विश्लेषण, अंतरफसल सुझाव, और डाउनलोड योग्य रिपोर्ट

        **डेटा स्रोत:** भारत सरकार MSP 2023-24, ICAR अनुशंसाएं, राज्य कृषि विभाग

        ---
        > ⚠️ **अस्वीकरण:** यह रिपोर्ट केवल सलाहकारी उद्देश्यों के लिए है।
        > वित्तीय निर्णय लेने से पहले अपने स्थानीय कृषि अधिकारी से सत्यापित करें।
        """
    )
    if st.button("🚀 शुरू करें — खेत का स्थान चुनें", type="primary", use_container_width=True):
        st.switch_page("pages/1_Land_Selection.py")
else:
    st.title("🌾 Farmer Revenue Optimizer")
    st.subheader("Higher income, lower costs — for your farm, in your language")
    st.markdown(
        """
        **What this app does:**

        - 🗺️ **Pinpoint your field** on a live satellite map
        - 📋 **Enter your crop details** — acreage, yield, and costs
        - 📊 **Get a full report:** revenue estimate, cost breakdown, intercropping ideas,
          seasonal tips, and a downloadable PDF

        **Data sources:** Government of India MSP 2023-24, ICAR recommendations, State Agriculture Departments

        ---
        > ⚠️ **Disclaimer:** This report is generated by an automated advisory system.
        > Always verify with your local agricultural officer or Krishi Vigyan Kendra (KVK)
        > before making financial decisions.
        """
    )
    if st.button("🚀 Get Started — Select Your Field", type="primary", use_container_width=True):
        st.switch_page("pages/1_Land_Selection.py")

st.divider()
col1, col2, col3 = st.columns(3)
with col1:
    st.markdown("### 🗺️ Step 1" if lang == "en" else "### 🗺️ चरण 1")
    st.markdown(
        "Select your field on the satellite map"
        if lang == "en"
        else "उपग्रह मानचित्र पर अपना खेत चुनें"
    )
with col2:
    st.markdown("### 📋 Step 2" if lang == "en" else "### 📋 चरण 2")
    st.markdown(
        "Enter crop, acreage, yield, and costs"
        if lang == "en"
        else "फसल, एकड़, उपज और लागत दर्ज करें"
    )
with col3:
    st.markdown("### 📊 Step 3" if lang == "en" else "### 📊 चरण 3")
    st.markdown(
        "Receive your personalized advisory report"
        if lang == "en"
        else "व्यक्तिगत सलाहकार रिपोर्ट प्राप्त करें"
    )
